import { DEMO_ORG_ID, ROUTES, to } from './paths'

export type ScreenStatus = 'ready' | 'wip' | 'planned'
export type Contour = 'entry' | 'cabinet' | 'employee' | 'guest'

export type ScreenVariant = { label: string; query: string }

export type Screen = {
  id: string
  title: string
  contour: Contour
  phase: number
  href: string
  status: ScreenStatus
  variants?: ScreenVariant[]
}

export const CONTOUR_LABEL: Record<Contour, string> = {
  entry: 'Вход и подключение',
  cabinet: 'Рабочий кабинет',
  employee: 'Кабинет сотрудника',
  guest: 'Гостевой путь',
}

const STATES: ScreenVariant[] = [
  { label: 'пусто', query: 'state=empty' },
  { label: 'ошибка', query: 'state=error' },
  { label: 'нет прав', query: 'state=denied' },
  { label: 'загрузка', query: 'state=loading' },
]

// Единый список экранов итерации: из него строится /pages, чтобы витрина не расходилась с маршрутами
export const SCREENS: Screen[] = [
  {
    id: 'today',
    title: 'Сегодня',
    contour: 'cabinet',
    phase: 1,
    href: to.today(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'один объект', query: 'objects=1' },
      { label: 'много объектов', query: 'objects=many' },
      { label: 'управляющий', query: 'role=manager' },
      ...STATES,
    ],
  },
  {
    id: 'calendar',
    title: 'Календарь',
    contour: 'cabinet',
    phase: 2,
    href: to.calendar(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'день', query: 'mode=day' },
      { label: 'месяц', query: 'mode=month' },
      { label: 'один объект', query: 'objects=1' },
      { label: 'сотрудник', query: 'role=employee' },
      ...STATES,
    ],
  },
  {
    id: 'bookings',
    title: 'Брони',
    contour: 'cabinet',
    phase: 2,
    href: to.bookings(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'конфликты', query: 'status=conflict' },
      { label: 'один объект', query: 'objects=1' },
      { label: 'управляющий', query: 'role=manager' },
      ...STATES,
    ],
  },
  {
    id: 'booking',
    title: 'Карточка брони',
    contour: 'cabinet',
    phase: 2,
    href: to.booking('b-1044', 'overview', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }, ...STATES],
  },
  {
    id: 'booking-unknown',
    title: 'Бронь: неизвестная оплата',
    contour: 'cabinet',
    phase: 2,
    href: to.booking('b-1050', 'payments', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'booking-conflict',
    title: 'Бронь: конфликт',
    contour: 'cabinet',
    phase: 2,
    href: to.booking('b-1042', 'overview', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'request',
    title: 'Прямая заявка (удержание)',
    contour: 'cabinet',
    phase: 2,
    href: to.request('r-201', DEMO_ORG_ID),
    status: 'ready',
    variants: STATES,
  },
  {
    id: 'tasks',
    title: 'Задачи',
    contour: 'cabinet',
    phase: 3,
    href: to.tasks(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'на проверке', query: 'tab=review' },
      { label: 'просроченные', query: 'tab=overdue' },
      { label: 'сотрудников', query: 'tab=team' },
      { label: 'один объект', query: 'objects=1' },
      ...STATES,
    ],
  },
  {
    id: 'task',
    title: 'Задача: с обязательным фото',
    contour: 'cabinet',
    phase: 3,
    href: to.task('t-301', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'исполнитель', query: 'role=employee' }, ...STATES],
  },
  {
    id: 'task-review',
    title: 'Задача: приёмка',
    contour: 'cabinet',
    phase: 3,
    href: to.task('t-305', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'task-overdue',
    title: 'Задача: просрочена',
    contour: 'cabinet',
    phase: 3,
    href: to.task('t-303', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'task-series',
    title: 'Серии задач',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeries(DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'один объект', query: 'objects=1' }, ...STATES],
  },
  {
    id: 'task-series-item',
    title: 'Редактор серии',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeriesItem('s-2', DEMO_ORG_ID),
    status: 'ready',
    variants: STATES,
  },
  {
    id: 'task-series-checkout',
    title: 'Серия «после выезда»',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeriesItem('s-3', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'task-series-new',
    title: 'Новая серия',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeriesItem('new', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'employee-tasks',
    title: 'Мои задачи сотрудника',
    contour: 'employee',
    phase: 3,
    href: to.tasks(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'сотрудник', query: 'role=employee' },
      { label: 'пусто', query: 'role=employee&state=empty' },
    ],
  },
  {
    id: 'employee-task',
    title: 'Задача сотрудника',
    contour: 'employee',
    phase: 3,
    href: to.task('t-301', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'в работе, фото', query: 'role=employee' }],
  },
  {
    id: 'employee-task-foreign',
    title: 'Чужая задача (нет прав)',
    contour: 'employee',
    phase: 3,
    href: to.task('t-303', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }],
  },
  {
    id: 'employee-task-returned',
    title: 'Задача: возврат на доработку',
    contour: 'employee',
    phase: 3,
    href: to.task('t-306', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'исполнитель', query: 'role=employee' }],
  },
  {
    id: 'employee-task-personal',
    title: 'Задача без объекта',
    contour: 'employee',
    phase: 3,
    href: to.task('t-304', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }],
  },
  {
    id: 'login',
    title: 'Вход',
    contour: 'entry',
    phase: 4,
    href: ROUTES.LOGIN,
    status: 'ready',
    variants: [
      { label: 'с возвратом', query: 'from=/app/org-volna/bookings/b-1044/overview' },
      { label: 'неверный код', query: 'state=error' },
      { label: 'блокировка', query: 'state=denied' },
    ],
  },
  {
    id: 'invite',
    title: 'Принятие приглашения',
    contour: 'entry',
    phase: 4,
    href: '/invite/vl-48a1',
    status: 'ready',
    variants: [
      { label: 'истекло', query: 'state=error' },
      { label: 'отозвано', query: 'state=denied' },
      { label: 'загрузка', query: 'state=loading' },
    ],
  },
  {
    id: 'workspaces',
    title: 'Выбор организации',
    contour: 'entry',
    phase: 4,
    href: ROUTES.WORKSPACES,
    status: 'ready',
    variants: [
      { label: 'нет организаций', query: 'state=empty' },
      { label: 'ошибка', query: 'state=error' },
      { label: 'загрузка', query: 'state=loading' },
    ],
  },
  {
    id: 'onboarding',
    title: 'Первые шаги владельца',
    contour: 'entry',
    phase: 4,
    href: to.onboarding(DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'properties',
    title: 'Объекты',
    contour: 'cabinet',
    phase: 4,
    href: to.properties(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'один объект', query: 'objects=1' },
      { label: 'управляющий', query: 'role=manager' },
      { label: 'сотрудник', query: 'role=employee' },
      ...STATES,
    ],
  },
  {
    id: 'property',
    title: 'Объект: сбой доступа к площадке',
    contour: 'cabinet',
    phase: 4,
    href: to.property('ligovsky', 'listings', DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'управляющий', query: 'role=manager' },
      ...STATES,
    ],
  },
  {
    id: 'property-linking',
    title: 'Объект: ссылка сохранена, доступ подтверждён',
    contour: 'cabinet',
    phase: 4,
    href: to.property('moika', 'listings', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'property-imported',
    title: 'Объект: импорт успешен, подготовка',
    contour: 'cabinet',
    phase: 4,
    href: to.property('neva', 'prep', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'property-direct',
    title: 'Объект: настройка публикации',
    contour: 'cabinet',
    phase: 4,
    href: to.property('moika', 'direct', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'управляющий', query: 'role=manager' }],
  },
  {
    id: 'property-published',
    title: 'Объект: опубликован, инструкции',
    contour: 'cabinet',
    phase: 4,
    href: to.property('ligovsky', 'instructions', DEMO_ORG_ID),
    status: 'ready',
  },
]
