import { DEMO_ORG_ID, ROUTES, to } from './paths'

export type ScreenStatus = 'ready' | 'wip' | 'planned'
export type Contour = 'entry' | 'cabinet' | 'employee' | 'guest' | 'specialist'

// href — вариант на другой записи того же экрана (другой специалист, другая бронь), а не query к основной
export type ScreenVariant = { label: string; query: string; href?: string }

export type Screen = {
  id: string
  title: string
  contour: Contour
  phase: number
  href: string
  status: ScreenStatus
  variants?: ScreenVariant[]
}

export const CONTOUR_LABEL: Record<Contour, string> = {
  entry: 'Вход и подключение',
  cabinet: 'Рабочий кабинет',
  employee: 'Кабинет сотрудника',
  guest: 'Гостевой путь',
  specialist: 'Кабинет специалиста',
}

const STATES: ScreenVariant[] = [
  { label: 'пусто', query: 'state=empty' },
  { label: 'ошибка', query: 'state=error' },
  { label: 'нет прав', query: 'state=denied' },
  { label: 'загрузка', query: 'state=loading' },
]

// Единый список экранов итерации: из него строится /pages, чтобы витрина не расходилась с маршрутами
export const SCREENS: Screen[] = [
  {
    id: 'today',
    title: 'Сегодня',
    contour: 'cabinet',
    phase: 1,
    href: to.today(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'один объект', query: 'objects=1' },
      { label: 'много объектов', query: 'objects=many' },
      { label: 'управляющий', query: 'role=manager' },
      ...STATES,
    ],
  },
  {
    id: 'calendar',
    title: 'Календарь',
    contour: 'cabinet',
    phase: 2,
    href: to.calendar(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'день', query: 'mode=day' },
      { label: 'месяц', query: 'mode=month' },
      { label: 'один объект', query: 'objects=1' },
      { label: 'сотрудник', query: 'role=employee' },
      ...STATES,
    ],
  },
  {
    id: 'bookings',
    title: 'Брони',
    contour: 'cabinet',
    phase: 2,
    href: to.bookings(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'конфликты', query: 'status=conflict' },
      { label: 'один объект', query: 'objects=1' },
      { label: 'управляющий', query: 'role=manager' },
      ...STATES,
    ],
  },
  {
    id: 'booking',
    title: 'Карточка брони',
    contour: 'cabinet',
    phase: 2,
    href: to.booking('b-1044', 'overview', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }, ...STATES],
  },
  {
    id: 'booking-unknown',
    title: 'Бронь: неизвестная оплата',
    contour: 'cabinet',
    phase: 2,
    href: to.booking('b-1050', 'payments', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'booking-conflict',
    title: 'Бронь: конфликт',
    contour: 'cabinet',
    phase: 2,
    href: to.booking('b-1042', 'overview', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'request',
    title: 'Прямая заявка (удержание)',
    contour: 'cabinet',
    phase: 2,
    href: to.request('r-201', DEMO_ORG_ID),
    status: 'ready',
    variants: STATES,
  },
  {
    id: 'tasks',
    title: 'Задачи',
    contour: 'cabinet',
    phase: 3,
    href: to.tasks(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'на проверке', query: 'tab=review' },
      { label: 'просроченные', query: 'tab=overdue' },
      { label: 'сотрудников', query: 'tab=team' },
      { label: 'один объект', query: 'objects=1' },
      ...STATES,
    ],
  },
  {
    id: 'task',
    title: 'Задача: с обязательным фото',
    contour: 'cabinet',
    phase: 3,
    href: to.task('t-301', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'исполнитель', query: 'role=employee' }, ...STATES],
  },
  {
    id: 'task-review',
    title: 'Задача: приёмка',
    contour: 'cabinet',
    phase: 3,
    href: to.task('t-305', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'task-overdue',
    title: 'Задача: просрочена',
    contour: 'cabinet',
    phase: 3,
    href: to.task('t-303', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'task-series',
    title: 'Серии задач',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeries(DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'один объект', query: 'objects=1' }, ...STATES],
  },
  {
    id: 'task-series-item',
    title: 'Редактор серии',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeriesItem('s-2', DEMO_ORG_ID),
    status: 'ready',
    variants: STATES,
  },
  {
    id: 'task-series-checkout',
    title: 'Серия «после выезда»',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeriesItem('s-3', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'task-series-new',
    title: 'Новая серия',
    contour: 'cabinet',
    phase: 3,
    href: to.taskSeriesItem('new', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'employee-tasks',
    title: 'Мои задачи сотрудника',
    contour: 'employee',
    phase: 3,
    href: to.tasks(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'сотрудник', query: 'role=employee' },
      { label: 'пусто', query: 'role=employee&state=empty' },
    ],
  },
  {
    id: 'employee-task',
    title: 'Задача сотрудника',
    contour: 'employee',
    phase: 3,
    href: to.task('t-301', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'в работе, фото', query: 'role=employee' }],
  },
  {
    id: 'employee-task-foreign',
    title: 'Чужая задача (нет прав)',
    contour: 'employee',
    phase: 3,
    href: to.task('t-303', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }],
  },
  {
    id: 'employee-profile',
    title: 'Профиль и помощь сотрудника',
    contour: 'employee',
    phase: 4,
    href: to.profile('workspaces', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }],
  },
  {
    id: 'employee-task-returned',
    title: 'Задача: возврат на доработку',
    contour: 'employee',
    phase: 3,
    href: to.task('t-306', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'исполнитель', query: 'role=employee' }],
  },
  {
    id: 'employee-task-personal',
    title: 'Задача без объекта',
    contour: 'employee',
    phase: 3,
    href: to.task('t-304', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }],
  },
  {
    id: 'login',
    title: 'Вход',
    contour: 'entry',
    phase: 4,
    href: ROUTES.LOGIN,
    status: 'ready',
    variants: [
      { label: 'с возвратом', query: 'from=/app/org-volna/bookings/b-1044/overview' },
      { label: 'неверный код', query: 'state=error' },
      { label: 'блокировка', query: 'state=denied' },
    ],
  },
  {
    id: 'invite',
    title: 'Принятие приглашения',
    contour: 'entry',
    phase: 4,
    href: '/invite/vl-48a1',
    status: 'ready',
    variants: [
      { label: 'истекло', query: 'state=error' },
      { label: 'отозвано', query: 'state=denied' },
      { label: 'загрузка', query: 'state=loading' },
    ],
  },
  // Выбор организации отключён: организация у пользователя одна
  // {
  //   id: 'workspaces',
  //   title: 'Выбор организации',
  //   contour: 'entry',
  //   phase: 4,
  //   href: ROUTES.WORKSPACES,
  //   status: 'ready',
  //   variants: [
  //     { label: 'нет организаций', query: 'state=empty' },
  //     { label: 'ошибка', query: 'state=error' },
  //     { label: 'загрузка', query: 'state=loading' },
  //   ],
  // },
  {
    id: 'org-new',
    title: 'Создание организации',
    contour: 'entry',
    phase: 4,
    href: ROUTES.ORG_NEW,
    status: 'ready',
  },
  {
    id: 'onboarding',
    title: 'Первые шаги владельца',
    contour: 'entry',
    phase: 4,
    href: to.onboarding(DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'properties',
    title: 'Объекты',
    contour: 'cabinet',
    phase: 4,
    href: to.properties(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'один объект', query: 'objects=1' },
      { label: 'управляющий', query: 'role=manager' },
      { label: 'сотрудник', query: 'role=employee' },
      ...STATES,
    ],
  },
  {
    id: 'property',
    title: 'Объект: сбой доступа к площадке',
    contour: 'cabinet',
    phase: 4,
    href: to.property('ligovsky', 'listings', DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'управляющий', query: 'role=manager' },
      ...STATES,
    ],
  },
  {
    id: 'property-linking',
    title: 'Объект: ссылка сохранена, доступ подтверждён',
    contour: 'cabinet',
    phase: 4,
    href: to.property('moika', 'listings', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'property-imported',
    title: 'Объект: импорт успешен, подготовка',
    contour: 'cabinet',
    phase: 4,
    href: to.property('neva', 'prep', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'property-direct',
    title: 'Объект: настройка публикации',
    contour: 'cabinet',
    phase: 4,
    href: to.property('moika', 'direct', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'управляющий', query: 'role=manager' }],
  },
  {
    id: 'property-published',
    title: 'Объект: опубликован, инструкции',
    contour: 'cabinet',
    phase: 4,
    href: to.property('ligovsky', 'instructions', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'profile',
    title: 'Профиль: личные данные',
    contour: 'cabinet',
    phase: 4,
    href: to.profile('about', DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'новый, без имени', query: 'state=empty' },
      { label: 'ошибка сохранения', query: 'state=error' },
      { label: 'сеанс завершён', query: 'state=denied' },
      { label: 'загрузка', query: 'state=loading' },
    ],
  },
  {
    id: 'profile-security',
    title: 'Профиль: вход и устройства',
    contour: 'cabinet',
    phase: 4,
    href: to.profile('security', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'новый, один сеанс', query: 'state=empty' }],
  },
  {
    id: 'profile-notifications',
    title: 'Профиль: уведомления и MAX',
    contour: 'cabinet',
    phase: 4,
    href: to.profile('notifications', DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'MAX не подключён', query: 'role=manager' },
      { label: 'сбой доставки MAX', query: 'role=employee' },
    ],
  },
  {
    id: 'profile-workspaces',
    title: 'Профиль: организации и кабинеты',
    contour: 'cabinet',
    phase: 4,
    href: to.profile('workspaces', DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'управляющий', query: 'role=manager' },
      { label: 'одна организация', query: 'state=empty' },
    ],
  },
  {
    id: 'host',
    title: 'Страница владельца',
    contour: 'guest',
    phase: 5,
    href: to.host(),
    status: 'ready',
    variants: [
      { label: 'пусто', query: 'state=empty' },
      { label: 'загрузка', query: 'state=loading' },
    ],
  },
  {
    id: 'host-property',
    title: 'Публичный объект',
    contour: 'guest',
    phase: 5,
    href: to.hostProperty('ligovsky'),
    status: 'ready',
    variants: [
      { label: 'даты заняты', query: 'from=2026-10-10&to=2026-10-13&guests=2' },
      { label: 'много гостей', query: 'guests=4' },
    ],
  },
  {
    id: 'host-checkout',
    title: 'Расчёт и оформление',
    contour: 'guest',
    phase: 5,
    href: `${to.hostCheckout()}?property=ligovsky&from=2026-10-15&to=2026-10-18&guests=2`,
    status: 'ready',
    variants: [
      { label: 'новые условия', query: 'state=error' },
      { label: 'даты заняли', query: 'state=denied' },
    ],
  },
  {
    id: 'guest-request',
    title: 'Заявка: удержание и оплата',
    contour: 'guest',
    phase: 5,
    href: to.guestRequest('r-201'),
    status: 'ready',
    variants: [
      { label: 'заявление о переводе', query: 'step=claim' },
      { label: 'проверка', query: 'step=review' },
      { label: 'истекло', query: 'step=expired' },
      { label: 'конфликт', query: 'step=conflict' },
    ],
  },
  {
    id: 'guest-bookings',
    title: 'Мои бронирования',
    contour: 'guest',
    phase: 5,
    href: to.guestBookings(),
    status: 'ready',
    variants: [
      { label: 'пусто', query: 'state=empty' },
      { label: 'чужая ссылка', query: 'state=denied' },
    ],
  },
  {
    id: 'guest-booking',
    title: 'Моя бронь',
    contour: 'guest',
    phase: 5,
    href: to.guestBooking('gb-1'),
    status: 'ready',
  },
  {
    id: 'guest-booking-past',
    title: 'Моя бронь: завершена',
    contour: 'guest',
    phase: 5,
    href: to.guestBooking('gb-0'),
    status: 'ready',
  },
  {
    id: 'guest-instructions',
    title: 'Инструкции',
    contour: 'guest',
    phase: 5,
    href: to.guestInstructions('gb-1'),
    status: 'ready',
    variants: [
      { label: 'закрыты по времени', query: 'state=denied' },
      { label: 'закрыты до оплаты', query: 'state=error' },
    ],
  },
  {
    id: 'money',
    title: 'Деньги: на проверке',
    contour: 'cabinet',
    phase: 6,
    href: to.moneyTab('review', DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'один объект', query: 'objects=1' },
      { label: 'управляющий', query: 'role=manager' },
      ...STATES,
    ],
  },
  {
    id: 'money-incoming',
    title: 'Деньги: поступления и корректировки',
    contour: 'cabinet',
    phase: 6,
    href: to.moneyTab('incoming', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'money-balances',
    title: 'Деньги: остатки',
    contour: 'cabinet',
    phase: 6,
    href: to.moneyTab('balances', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'money-deposits',
    title: 'Деньги: залоги',
    contour: 'cabinet',
    phase: 6,
    href: to.moneyTab('deposits', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'money-refunds',
    title: 'Деньги: возвраты',
    contour: 'cabinet',
    phase: 6,
    href: to.moneyTab('refunds', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'settings-team',
    title: 'Настройки: команда и доступ',
    contour: 'cabinet',
    phase: 6,
    href: to.settings('team', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'пусто — работаю один', query: 'state=empty' }, { label: 'управляющий', query: 'role=manager' }],
  },
  {
    id: 'settings-channels',
    title: 'Настройки: площадки',
    contour: 'cabinet',
    phase: 6,
    href: to.settings('channels', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'не подключены', query: 'state=empty' }],
  },
  {
    id: 'settings-page',
    title: 'Настройки: моя страница',
    contour: 'cabinet',
    phase: 6,
    href: to.settings('page', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'settings-requisites',
    title: 'Настройки: реквизиты',
    contour: 'cabinet',
    phase: 6,
    href: to.settings('requisites', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'нет реквизитов', query: 'state=empty' }],
  },
  {
    id: 'settings-notifications',
    title: 'Настройки: уведомления и MAX',
    contour: 'cabinet',
    phase: 6,
    href: to.settings('notifications', DEMO_ORG_ID),
    status: 'ready',
  },
  {
    id: 'settings-export',
    title: 'Настройки: выгрузки',
    contour: 'cabinet',
    phase: 6,
    href: to.settings('export', DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'управляющий — нет права', query: 'role=manager' }],
  },
  {
    id: 'notifications',
    title: 'Центр уведомлений',
    contour: 'cabinet',
    phase: 6,
    href: to.notifications(DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'сотрудник', query: 'role=employee' }, ...STATES],
  },
  {
    id: 'help',
    title: 'Помощь',
    contour: 'cabinet',
    phase: 6,
    href: to.help(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'из записи', query: 'record=b-1045' },
      { label: 'сотрудник', query: 'role=employee' },
    ],
  },
  {
    id: 'specialists',
    title: 'Специалисты: поиск',
    contour: 'cabinet',
    phase: 7,
    href: to.specialists(DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'сантехника', query: 'category=plumbing' },
      { label: 'пусто по фильтру', query: 'category=photo&district=kurortny&service=video' },
      { label: 'сбой обмена', query: 'access=stale' },
      { label: 'доступ закрыт', query: 'access=closed' },
      { label: 'нет даты брони', query: 'access=pending' },
      { label: 'сотрудник', query: 'role=employee' },
      ...STATES,
    ],
  },
  {
    id: 'specialist',
    title: 'Профиль специалиста',
    contour: 'cabinet',
    phase: 7,
    href: to.specialist('sp-1', DEMO_ORG_ID),
    status: 'ready',
    variants: [
      { label: 'ждёт ответа', query: '', href: to.specialist('sp-2', DEMO_ORG_ID) },
      { label: 'без отзывов, контакты открыты', query: '', href: to.specialist('sp-3', DEMO_ORG_ID) },
      { label: 'временно недоступен', query: '', href: to.specialist('sp-4', DEMO_ORG_ID) },
      { label: 'отказ', query: '', href: to.specialist('sp-5', DEMO_ORG_ID) },
      { label: 'истёк, нет канала', query: '', href: to.specialist('sp-6', DEMO_ORG_ID) },
      { label: 'скрыт', query: '', href: to.specialist('sp-7', DEMO_ORG_ID) },
      { label: 'оценка недоступна', query: 'review=denied' },
      { label: 'доступ закрыт', query: 'access=closed' },
    ],
  },
  {
    id: 'specialist-favorites',
    title: 'Специалисты: избранное',
    contour: 'cabinet',
    phase: 7,
    href: to.specialistFavorites(DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'пусто', query: 'state=empty' }, { label: 'доступ закрыт', query: 'access=closed' }],
  },
  {
    id: 'specialist-requests',
    title: 'Специалисты: мои обращения',
    contour: 'cabinet',
    phase: 7,
    href: to.specialistRequests(DEMO_ORG_ID),
    status: 'ready',
    variants: [{ label: 'доступ закрыт', query: 'access=closed' }, { label: 'ждут ответа', query: 'status=pending' }, ...STATES],
  },
  {
    id: 'specialist-profile',
    title: 'Мой профиль специалиста',
    contour: 'specialist',
    phase: 7,
    href: to.specialistProfile(),
    status: 'ready',
    variants: [
      { label: 'на модерации', query: 'moderation=pending' },
      { label: 'отклонён', query: 'moderation=rejected' },
    ],
  },
  {
    id: 'specialist-inbox',
    title: 'Обращения специалисту',
    contour: 'specialist',
    phase: 7,
    href: to.specialistInbox(),
    status: 'ready',
    variants: [
      { label: 'пусто', query: 'state=empty' },
      { label: 'ошибка', query: 'state=error' },
      { label: 'заблокирован', query: 'state=denied' },
    ],
  },
  {
    id: 'specialist-reviews',
    title: 'Отзывы специалиста',
    contour: 'specialist',
    phase: 7,
    href: to.specialistReviews(),
    status: 'ready',
    variants: [{ label: 'без отзывов', query: 'state=empty' }, { label: 'загрузка', query: 'state=loading' }],
  },
]
